<?php 
	echo $this->doctype(); 
	/** @var \TwitterBootstrapAPI\View\Helper\Bootstrap $oTwitterBootstrap **/
	$oTwitterBootstrap = $this->bootstrap();
	/** @var \TwitterBootstrapAPI\View\Helper\Components $oComponents **/
	$oComponents = $this->Components();
?>
<html>
<head>
	<meta charset="utf-8">
	<?php echo $this->headTitle('[BB] '. $this->translate($oTwitterBootstrap->AppTitle()))->setSeparator(' - ')->setAutoEscape(false) ?>
	<?php 
		echo $this->headMeta()
			->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
			->appendName('viewport', 'width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui')
			->appendName('description', 'ZF2 Base Application')
			->appendName('author', '[drgon-projecs.net]')
		;
	?>
	<?php 
		$themePath = "assets/themes/adminlte/";
		$this->headLink(array(
				'rel' => 'shortcut icon', 
				'type' => 'image/vnd.microsoft.icon', 
				'href' => $this->basePath($themePath . $oTwitterBootstrap->AppFavicon())
 			))
 			/*->append((object)array(
				'rel' => 'apple-touch-icon', 
				'href' => $this->basePath($themePath . 'images/apple-touch-icon.png')
 			))*/
		;
		$this->headLink()
			->appendStylesheet($this->basePath($themePath . 'css/bootstrap/css/bootstrap.min.css'))
			->appendStylesheet('https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css')
			->appendStylesheet('https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css')
			->appendStylesheet($this->basePath($themePath . 'js/plugins/jvectormap/jquery-jvectormap-1.2.2.css'))
			->appendStylesheet($this->basePath($themePath . 'js/plugins/datatables/dataTables.bootstrap.css'))
			->appendStylesheet($this->basePath($themePath . 'css/AdminLTE.min.css'))
			->appendStylesheet($this->basePath($themePath . 'css/skins/_all-skins.min.css'))
			->appendStylesheet($this->basePath($themePath . 'css/fontawesome/css/font-awesome.min.css'))
		;
		$cssfiles = $oTwitterBootstrap->Config()->get('app')->get('css');
		if (is_array($cssfiles) || ($cssfiles instanceof \Zend\Config\Config)) foreach ($cssfiles as $key => $file) {
			$this->headLink()->appendStylesheet($this->basePath($file));
		}
		echo $this->headLink();
	?>
	<?php 
		$this->headScript()
			->appendFile($this->basePath($themePath . 'vendor/html5shiv//html5shiv.js'),	'text/javascript', array('conditional' => 'lt IE 9',))
			//->appendFile($this->basePath($themePath . 'vendor/media-match/media.match.min.js'), 'text/javascript', array('conditional' => 'lt IE 10',))
			->appendFile($this->basePath($themePath . 'vendor/respond/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
			//->appendFile($this->basePath($themePath . 'vendor/modernizr/modernizr.js'), 'text/javascript')
			//->appendFile($this->basePath($themePath . 'vendor/breakpoints/breakpoints.js'), 'text/javascript')
		;
		echo $this->headScript();
	?>
</head>
<body class="hold-transition skin-blue-light sidebar-mini sidebar-collapse">
	<div class="wrapper">
	
		<header class="main-header">
	
			<!-- Logo -->
			<a href="/" class="logo">
				<!-- mini logo for sidebar mini 50x50 pixels -->
				<span class="logo-mini"><?php echo $oTwitterBootstrap->AppTitle(true); ?></span>
				<!-- logo for regular state and mobile devices -->
				<span class="logo-lg"><?php echo $oTwitterBootstrap->AppTitle(); ?></span>
			</a>
		
			<!-- Header Navbar: style can be found in header.less -->
			<nav class="navbar navbar-static-top" role="navigation">
				<!-- Sidebar toggle button-->
				<a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
					<span class="sr-only">Toggle navigation</span>
				</a>
				<!-- Navbar Right Menu -->
				<div class="navbar-custom-menu">
					<?php echo $this->partial('partial/navbar-toolbar-right.phtml', array("themePath" => $themePath)); ?>
					<?php 
						$oBootstrapComponents = $this->bootstrap()->Components();
						$oLocaleMenu = $oBootstrapComponents->Languagemenu()
							->setUlClass('nav navbar-nav navbar-right')
							->setIconPrefixClass('flag-icon flag-icon-')
						;
						echo $oLocaleMenu->render(); 
					?>
				</div>
			</nav>
			
		</header>
		
		<!-- Left side column. contains the logo and sidebar -->
		<aside class="main-sidebar">
			<!-- sidebar: style can be found in sidebar.less -->
			<section class="sidebar">
				<!-- Sidebar user panel -->
				<div class="user-panel">
					<div class="pull-left image">
						<img src="/assets/themes/adminlte/img/user2-160x160.jpg" class="img-circle" alt="User Image">
					</div>
					<div class="pull-left info">
						<p>Alexander Pierce</p>
						<a href="#"><i class="fa fa-circle text-success"></i> Online</a>
					</div>
				</div>
				<!-- search form -->
				<form action="#" method="get" class="sidebar-form">
					<div class="input-group">
						<input type="text" name="q" class="form-control" placeholder="Search...">
						<span class="input-group-btn">
							<button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
							</button>
						</span>
					</div>
				</form>
				<!-- /.search form -->
				
				<!-- sidebar menu: : style can be found in sidebar.less -->
				<ul class="sidebar-menu">
					<li class="header">MAIN NAVIGATION</li>
				</ul>
				
				<?php 
					$navBarPartial = array('partial/bootstrap-navbar.phtml', 'default');
					$htmlifyPartial = array('partial/sidebar-menu-htmlify.phtml', 'default');
					$oNavBar = $oTwitterBootstrap->Navbar('navigation')
							->setMinDepth(0)
							->setMaxDepth(3)
							//->setPartial($navBarPartial)
							->setUlClass('sidebar-menu')
							->setSubUlClass('treeview-menu')
							->setSubUlClassLevel1('treeview-menu')
							->setDefaultLiClass('treeview')
							->setSubLiClass('treeview')
							->setSubLiClassLevel0('treeview')
							->setLiActiveClass('active')
							->setIconPrefixClass('fa fa-')
							//->setIconPrefixClass('glyphicon glyphicon-')
							->setHtmlifyPartial($htmlifyPartial)
							//->setHrefSubToggleOverride('javascript:void(0);')
					;
					echo $oNavBar->render();
				?>
			</section>
			<!-- /.sidebar -->
		</aside>
	
		<!-- Content Wrapper. Contains page content -->
		<div class="content-wrapper">
			<!-- Content Header (Page header) -->
			<section class="content-header">
				<h1>
					<?php echo $this->escapeHtml(isset($this->title) ? $this->title." - " : ""); ?>
					<small>Dashboard
						<small>Version 2.0</small>
					</small>
				</h1>

					<?php 
						$oBreadcrumbs = $oTwitterBootstrap->Breadcrumbs('navigation')
							->setHeader( $this->translate('you are here') )
							->setMinDepth(0)
						;
						echo $oBreadcrumbs->render(); 
					?>
			</section>
		
			<!-- Main content -->
			<section class="content">
				<?php
					$params = $this->getHelperPluginManager()
						->getServiceLocator()
						->get('Application')
						->getMvcEvent()
						->getRouteMatch()
						->getParams();
					if ($params["action"] == "index") {
						echo $this->content;
					} else {
						$panelLayout = $oComponents->Panel()
						->setHeader( (isset($this->title) ? $this->title : "") )
						->setContent(
								array(
										'tagname' => 'div',
										'classnames' => 'panel-body alert-wrap',
										'content' => $this->content,
								)
							)
						;
						
						echo $panelLayout;
					}
				?>
			</section>
			<!-- /.content -->
		</div>
		<!-- /.content-wrapper -->
	
		<footer class="main-footer">
			<span class="copyright">&copy; <?php echo date('Y') ?> by <a href="//dragon-projects.net" target="_blank">[dragon-projects.net]</a> - <?php echo $this->translate('All rights reserved.') ?></span>
			<span class="poweredby pull-right">
				Powered by &nbsp;
				<a href="http://php.net" target="_blank"><img src="<?php echo $this->basePath($themePath.'img/php-logo.gif') ?>" height="20" alt="php" /></a> &nbsp;
				<a href="http://framework.zend.com" target="_blank"><img src="<?php echo $this->basePath($themePath.'img/zf2-logo.png') ?>" height="16" alt="ZendFramework 2" /></a> &nbsp;
				<a href="http://www.w3.org/html/" target="_blank"><img src="<?php echo $this->basePath($themePath.'img/html5-badge-h-solo.png') ?>" height="16" alt="HTML5" /></a> &nbsp;
				<a href="http://jquery.com" target="_blank"><img src="<?php echo $this->basePath($themePath.'img/jquery-logo.png') ?>" height="16" alt="jQuery" /></a>
			</span>
		</footer>
	
		<?php echo $this->partial('partial/asidebar-controlbar-right.phtml', array("themePath" => $themePath)); ?>
	
	</div>
	<!-- ./wrapper -->

	<?php 
		$this->inlineScript()
	
	// <!-- Scripts -->
			->appendFile($this->basePath($themePath . 'js/plugins/jQuery/jQuery-2.1.4.min.js'))
			->appendFile($this->basePath($themePath . 'css/bootstrap/js/bootstrap.min.js'))
			->appendFile($this->basePath($themePath . 'js/plugins/fastclick/fastclick.js'))
			->appendFile($this->basePath($themePath . 'js/plugins/sparkline/jquery.sparkline.min.js'))
			->appendFile($this->basePath($themePath . 'js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js'))
			->appendFile($this->basePath($themePath . 'js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js'))
			->appendFile($this->basePath($themePath . 'js/plugins/slimScroll/jquery.slimscroll.min.js'))
			->appendFile($this->basePath($themePath . 'js/plugins/chartjs/Chart.min.js'))
			
				->appendFile($this->basePath($themePath . '../zf2-basic/js/datatables/js/jquery.dataTables.min.js'))
			->appendFile($this->basePath($themePath . 'js/app.min.js'))
			//->appendFile($this->basePath($themePath . 'js/pages/dashboard.js'))
			//->appendFile($this->basePath($themePath . 'js/demo.js'))
			
			->appendFile($this->basePath($themePath . '../zf2-basic/js/app.js'))
		;
		$jsfiles = $oTwitterBootstrap->Config()->get('app')->get('js');
		if (is_array($jsfiles) || ($jsfiles instanceof \Zend\Config\Config)) foreach ($jsfiles as $key => $file) {
			$this->inlineScript()->appendFile($this->basePath($file));
		}
		echo $this->inlineScript();
	?>
	
</body>
</html>
